config/routes.rb
Rails.application.routes.draw do
  root 'signatures#index'
  get 'pages/index'
  get 'pages/lorem_ipsum'
  get 'hello_world/index'
  resources :signatures, only: [:index, :new, :create]
  get 'lorem_ipsum' => 'signatures#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signature.rb
class Signature < ApplicationRecord
	validates_length_of :name, maximum: 40, message: 'The signature can\'t be longer than 40 characters'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def lorem_ipsum
  end
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  
  def index
  	@signatures = Signature.all
  end
 
  def new
    @signature = Signature.new
  end
 
  def create
    @signature = Signature.create(name: params[:signature][:name])
    index
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_world_helper.rb
module HelloWorldHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/hello_world/index.html.erb
<h1>HelloWorld#index</h1>
<p>Hello, world!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/signatures/index.html.erb
<% if @signature && @signature.errors.any? %>
  <h2>Error during the signature:</h2>
  <ul>
  <% @signature.errors.each do |attr, msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<%end %>

<h1> Signatures </h1>
 
<ul>
  <% @signatures.each do |s| %>
<li> <%= s.name %></li>
  <%end %>
</ul>
 
<h1>Sign the Lorem</h1>
 
<%= link_to 'Take me to lorem', lorem_ipsum_path %>

app/views/signatures/new.html.erb
<h1>Here comes the Lorem!</h1>
 
<%= Forgery('lorem_ipsum').paragraphs(1) %>
 
<%= form_for @signature do |f| %>
  Signature: <%= f.text_field :name, id: :signature %>
<%= submit_tag 'Submit' %>
<% end %>